ARG version
FROM almalinux:${version:-9}
ENV COURSE="DevOps"\
    DURATION="120HRS"
ARG TRAINER="Siva"
RUN echo "Hi, course is ${COURSE},duration is ${DURATION},trainer is ${TRAINER}"
CMD ["sleep","1000"]
